/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sensor.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sensor.pb-c.h"
void   sensor__single_phase__init
                     (Sensor__SinglePhase         *message)
{
  static const Sensor__SinglePhase init_value = SENSOR__SINGLE_PHASE__INIT;
  *message = init_value;
}
size_t sensor__single_phase__get_packed_size
                     (const Sensor__SinglePhase *message)
{
  assert(message->base.descriptor == &sensor__single_phase__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensor__single_phase__pack
                     (const Sensor__SinglePhase *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensor__single_phase__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensor__single_phase__pack_to_buffer
                     (const Sensor__SinglePhase *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensor__single_phase__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensor__SinglePhase *
       sensor__single_phase__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensor__SinglePhase *)
     protobuf_c_message_unpack (&sensor__single_phase__descriptor,
                                allocator, len, data);
}
void   sensor__single_phase__free_unpacked
                     (Sensor__SinglePhase *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensor__single_phase__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sensor__three_phase__init
                     (Sensor__ThreePhase         *message)
{
  static const Sensor__ThreePhase init_value = SENSOR__THREE_PHASE__INIT;
  *message = init_value;
}
size_t sensor__three_phase__get_packed_size
                     (const Sensor__ThreePhase *message)
{
  assert(message->base.descriptor == &sensor__three_phase__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensor__three_phase__pack
                     (const Sensor__ThreePhase *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensor__three_phase__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensor__three_phase__pack_to_buffer
                     (const Sensor__ThreePhase *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensor__three_phase__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensor__ThreePhase *
       sensor__three_phase__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensor__ThreePhase *)
     protobuf_c_message_unpack (&sensor__three_phase__descriptor,
                                allocator, len, data);
}
void   sensor__three_phase__free_unpacked
                     (Sensor__ThreePhase *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensor__three_phase__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sensor__device_register__init
                     (Sensor__DeviceRegister         *message)
{
  static const Sensor__DeviceRegister init_value = SENSOR__DEVICE_REGISTER__INIT;
  *message = init_value;
}
size_t sensor__device_register__get_packed_size
                     (const Sensor__DeviceRegister *message)
{
  assert(message->base.descriptor == &sensor__device_register__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensor__device_register__pack
                     (const Sensor__DeviceRegister *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensor__device_register__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensor__device_register__pack_to_buffer
                     (const Sensor__DeviceRegister *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensor__device_register__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensor__DeviceRegister *
       sensor__device_register__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensor__DeviceRegister *)
     protobuf_c_message_unpack (&sensor__device_register__descriptor,
                                allocator, len, data);
}
void   sensor__device_register__free_unpacked
                     (Sensor__DeviceRegister *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensor__device_register__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sensor__message__init
                     (Sensor__Message         *message)
{
  static const Sensor__Message init_value = SENSOR__MESSAGE__INIT;
  *message = init_value;
}
size_t sensor__message__get_packed_size
                     (const Sensor__Message *message)
{
  assert(message->base.descriptor == &sensor__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensor__message__pack
                     (const Sensor__Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensor__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensor__message__pack_to_buffer
                     (const Sensor__Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensor__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensor__Message *
       sensor__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensor__Message *)
     protobuf_c_message_unpack (&sensor__message__descriptor,
                                allocator, len, data);
}
void   sensor__message__free_unpacked
                     (Sensor__Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensor__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sensor__single_phase__field_descriptors[14] =
{
  {
    "message_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Sensor__SinglePhase, message_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sn",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Sensor__SinglePhase, sn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phase",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Sensor__SinglePhase, phase),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "currentEffectiveValue",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensor__SinglePhase, currenteffectivevalue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "batteryVoltage",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensor__SinglePhase, batteryvoltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frequency",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensor__SinglePhase, frequency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperature",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensor__SinglePhase, temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "humidity",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensor__SinglePhase, humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "activePower",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Sensor__SinglePhase, activepower),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reactivePower",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Sensor__SinglePhase, reactivepower),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "apparentPower",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Sensor__SinglePhase, apparentpower),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "activeEnergy",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Sensor__SinglePhase, activeenergy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "apparentEnergy",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Sensor__SinglePhase, apparentenergy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instantaneousCurrent",
    14,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Sensor__SinglePhase, n_instantaneouscurrent),
    offsetof(Sensor__SinglePhase, instantaneouscurrent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensor__single_phase__field_indices_by_name[] = {
  11,   /* field[11] = activeEnergy */
  8,   /* field[8] = activePower */
  12,   /* field[12] = apparentEnergy */
  10,   /* field[10] = apparentPower */
  4,   /* field[4] = batteryVoltage */
  3,   /* field[3] = currentEffectiveValue */
  5,   /* field[5] = frequency */
  7,   /* field[7] = humidity */
  13,   /* field[13] = instantaneousCurrent */
  0,   /* field[0] = message_type */
  2,   /* field[2] = phase */
  9,   /* field[9] = reactivePower */
  1,   /* field[1] = sn */
  6,   /* field[6] = temperature */
};
static const ProtobufCIntRange sensor__single_phase__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor sensor__single_phase__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensor.SinglePhase",
  "SinglePhase",
  "Sensor__SinglePhase",
  "sensor",
  sizeof(Sensor__SinglePhase),
  14,
  sensor__single_phase__field_descriptors,
  sensor__single_phase__field_indices_by_name,
  1,  sensor__single_phase__number_ranges,
  (ProtobufCMessageInit) sensor__single_phase__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensor__three_phase__field_descriptors[1] =
{
  {
    "singlePhases",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Sensor__ThreePhase, n_singlephases),
    offsetof(Sensor__ThreePhase, singlephases),
    &sensor__single_phase__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensor__three_phase__field_indices_by_name[] = {
  0,   /* field[0] = singlePhases */
};
static const ProtobufCIntRange sensor__three_phase__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sensor__three_phase__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensor.ThreePhase",
  "ThreePhase",
  "Sensor__ThreePhase",
  "sensor",
  sizeof(Sensor__ThreePhase),
  1,
  sensor__three_phase__field_descriptors,
  sensor__three_phase__field_indices_by_name,
  1,  sensor__three_phase__number_ranges,
  (ProtobufCMessageInit) sensor__three_phase__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensor__device_register__field_descriptors[2] =
{
  {
    "sn",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Sensor__DeviceRegister, sn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Sensor__DeviceRegister, device_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensor__device_register__field_indices_by_name[] = {
  1,   /* field[1] = device_type */
  0,   /* field[0] = sn */
};
static const ProtobufCIntRange sensor__device_register__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sensor__device_register__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensor.DeviceRegister",
  "DeviceRegister",
  "Sensor__DeviceRegister",
  "sensor",
  sizeof(Sensor__DeviceRegister),
  2,
  sensor__device_register__field_descriptors,
  sensor__device_register__field_indices_by_name,
  1,  sensor__device_register__number_ranges,
  (ProtobufCMessageInit) sensor__device_register__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensor__message__field_descriptors[4] =
{
  {
    "message_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Sensor__Message, message_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "singlePhase",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Sensor__Message, singlephase),
    &sensor__single_phase__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "threePhase",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Sensor__Message, threephase),
    &sensor__three_phase__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "register",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Sensor__Message, register_),
    &sensor__device_register__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensor__message__field_indices_by_name[] = {
  0,   /* field[0] = message_type */
  3,   /* field[3] = register */
  1,   /* field[1] = singlePhase */
  2,   /* field[2] = threePhase */
};
static const ProtobufCIntRange sensor__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sensor__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensor.Message",
  "Message",
  "Sensor__Message",
  "sensor",
  sizeof(Sensor__Message),
  4,
  sensor__message__field_descriptors,
  sensor__message__field_indices_by_name,
  1,  sensor__message__number_ranges,
  (ProtobufCMessageInit) sensor__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
